{{- if .Values.cr.created }}
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: {{ .Release.Namespace | quote }}
spec:
  certificateRotateStrategy: {}
  configuration:
    {{- nindent 4 (toYaml .Values.cr.configuration )}}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
{{- end }}
